version: "3.8"

services:
  streamlit:
    build: .
    volumes:
      - .:/stream1
    working_dir: /stream1
    ports:
      - "8501:8501"
    environment:
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
