name: Keep Streamlit App Alive
on:
  schedule:
    # Каждые 8 часов: в 00:00, 08:00, 16:00 UTC
    - cron: "0 */8 * * *"
  workflow_dispatch: # Позволяет запуск вручную из GitHub UI

jobs:
  ping:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Ping Streamlit App
        run: |
          echo "🚀 Starting health check at $(date)"
          echo "Target URL: https://rfpopulate.streamlit.app"

          # Функция для проверки приложения
          check_app() {
            local attempt=$1
            echo "📡 Attempt $attempt/3..."
            
            # Выполняем запрос с таймаутом и получаем код ответа
            response=$(curl -s -o /dev/null -w "%{http_code}:%{time_total}" \
                       --max-time 45 \
                       --connect-timeout 15 \
                       --retry 0 \
                       https://rfpopulate.streamlit.app)
            
            http_code=$(echo $response | cut -d':' -f1)
            time_total=$(echo $response | cut -d':' -f2)
            
            echo "HTTP Code: $http_code | Response Time: ${time_total}s"
            
            if [ "$http_code" -eq 200 ]; then
              echo "✅ App is healthy and responding!"
              return 0
            else
              echo "❌ App returned HTTP code: $http_code"
              return 1
            fi
          }

          # Пытаемся подключиться 3 раза с интервалом
          success=false
          for i in {1..3}; do
            if check_app $i; then
              success=true
              break
            else
              if [ $i -lt 3 ]; then
                echo "⏳ Waiting 30 seconds before retry..."
                sleep 30
              fi
            fi
          done

          # Итоговый результат
          if [ "$success" = true ]; then
            echo "🎉 Health check completed successfully!"
            echo "App is awake and ready to serve users."
          else
            echo "💔 All attempts failed. App might be experiencing issues."
            echo "Check your Streamlit app manually: https://rfpopulate.streamlit.app"

            # Попытка перезапуска приложения через API (если доступно)
            echo "🔄 Attempting to restart application..."
            # Здесь можно добавить команды для перезапуска через API
            # curl -X POST https://api.streamlit.io/restart -H "Authorization: Bearer ${{ secrets.STREAMLIT_API_TOKEN }}"

            exit 1
          fi

          echo "✨ Health check finished at $(date)"
