name: Ping Streamlit App

on:
  schedule:
    - cron: "0 7 * * 0" # Каждое воскресенье в 4:00 UTC (7:00 по Москве)
  workflow_dispatch: # Позволяет запуск вручную из GitHub UI

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Streamlit App
        run: |
          curl -sSf https://aimnew-stream1.streamlit.app || echo "Ping failed"
